{
 "title": "cpu usage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "lo_recv_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lo_recv_bytes\nFROM cpu_usage\nORDER BY time"
    }
   ]
  },
  {
   "title": " lo_recv_pckts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lo_recv_pckts\nFROM cpu_usage\nORDER BY time"
    }
   ]
  },
  {
   "title": "wlp7s0_recv_frms",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wlp7s0_recv_frms\nFROM cpu_usage\nORDER BY time"
    }
   ]
  },
  {
   "title": "wlp7s0_recv_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wlp7s0_recv_bytes\nFROM cpu_usage\nORDER BY time"
    }
   ]
  }
 ]
}