{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "network received bytes (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lo_recv_bytes\nFROM usage_network\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wlp7s0_recv_bytes\nFROM usage_network\nORDER BY time"
    }
   ]
  },
  {
   "title": "network received bytes (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lo_trns_bytes\nFROM usage_network\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wlp7s0_trns_bytes\nFROM usage_network\nORDER BY time"
    }
   ]
  },
  {
   "title": "network received frames",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wlp7s0_recv_frms\nFROM usage_network\nORDER BY time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  cpu_usage\nFROM usage_cpu\nORDER BY time"
    }
   ]
  },
  {
   "title": "network received packets",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lo_recv_pckts\nFROM usage_network\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  id AS \"time\",\n  wlp7s0_recv_pckts\nFROM usage_network\nORDER BY id"
    }
   ]
  },
  {
   "title": "network transmitted packets",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lo_trns_pckts\nFROM usage_network\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wlp7s0_trns_pckts\nFROM usage_network\nORDER BY time"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  disk_usage\nFROM usage_disk\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  free_disk\nFROM usage_disk\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  used_disk\nFROM usage_disk\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  total_disk\nFROM usage_disk\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "stat",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  available_memory\nFROM usage_memory\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  free_memory\nFROM usage_memory\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  used_memory\nFROM usage_memory\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  cached_memory\nFROM usage_memory\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  shared_memory\nFROM usage_memory\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  total_memory\nFROM usage_memory\nORDER BY time"
    }
   ]
  }
 ]
}